version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: web2pdf
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - ENV=local-docker